default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: weight_lifting_pro_development

test:
  <<: *default
  database: weight_lifting_pro_test

production:
  <<: *default
  database: weight_lifting_pro_production
  username: weight_lifting_pro
  password: <%= ENV['WEIGHT_LIFTING_PRO_DATABASE_PASSWORD'] %>
